export const CATEGORIES_GETTING_ALL = "CATEGORIES_GETTING_ALL";
export const CATEGORIES_GETTING_SUCCESS = "CATEGORIES_GETTING_SUCCESS";
export const CATEGORIES_GETTING_ERROR = "CATEGORIES_GETTING_ERROR";
